name: Send News to Telegram
on:
  push:
    paths:
      - news.md
    branches:
      - main

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send news to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 send_telegram.py
